import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export const metadata = {
  title: "Before/After Examples - GitReady",
  description:
    "Real before and after examples of GitHub profile improvements. See what changes make the biggest impact.",
};

const examples = [
  {
    title: "Junior Developer",
    context: "Recent CS graduate looking for their first role",
    timeInvested: "~6 hours over one weekend",
    before: [
      "Bio: empty",
      "Avatar: default GitHub identicon",
      "Repos: 23 repos, most named 'assignment-1', 'lab-3'",
      "READMEs: none",
      "Pinned repos: none",
      "Last commit: 4 months ago",
    ],
    after: [
      "Bio: 'CS graduate | Full-stack developer | React, Python, PostgreSQL'",
      "Avatar: professional headshot",
      "Repos: archived school assignments, 5 polished projects visible",
      "READMEs: detailed README on each with screenshots and setup instructions",
      "Pinned: 4 best projects including capstone and a personal project",
      "Last commit: 2 days ago",
    ],
    changes: [
      "Archived 18 school assignment repos",
      "Renamed remaining repos to descriptive names",
      "Added profile README with skills badges and project links",
      "Wrote detailed READMEs for each pinned project",
      "Added screenshots and demo GIFs",
      "Started contributing to an open-source project weekly",
    ],
    result: "Received 3 recruiter messages on LinkedIn within 2 weeks of updating the profile.",
  },
  {
    title: "Career Changer",
    context: "Marketing professional transitioning to frontend development",
    timeInvested: "~8 hours over 2 weeks",
    before: [
      "Bio: 'Learning to code'",
      "Avatar: vacation photo",
      "Repos: 8 tutorial follow-along repos forked from course instructors",
      "READMEs: auto-generated by create-react-app",
      "Contribution graph: mostly empty with random bursts",
      "No profile README",
    ],
    after: [
      "Bio: 'Frontend Developer | React & TypeScript | Ex-Marketing, now building products'",
      "Avatar: professional headshot",
      "Repos: 3 original projects + 2 meaningful forks with contributions",
      "READMEs: custom README on each project with problem/solution framing",
      "Contribution graph: consistent 3-4 days per week",
      "Profile README highlighting transferable skills and unique perspective",
    ],
    changes: [
      "Deleted forked tutorial repos (they showed no original work)",
      "Built 3 original projects solving real problems from their marketing background",
      "Updated bio to highlight career narrative, not 'learning status'",
      "Used the 'Portfolio Project' README template for each project",
      "Started making small contributions to a popular React component library",
      "Added LinkedIn and portfolio links to profile",
    ],
    result: "Landed an interview at a startup that valued the marketing + dev combination.",
  },
  {
    title: "Data Science Student",
    context: "Final year student applying for data science internships",
    timeInvested: "~5 hours over 3 days",
    before: [
      "Bio: 'Student'",
      "Avatar: anime character",
      "Repos: Jupyter notebooks with no descriptions",
      "READMEs: only 'Created with Jupyter' auto-text",
      "Repo names: 'ML_HW2', 'final_project_v3_FINAL'",
      "No visible tech stack or skills",
    ],
    after: [
      "Bio: 'Data Science | Python, SQL, TensorFlow | University of XYZ '25'",
      "Avatar: professional photo",
      "Repos: 4 well-structured ML projects with clear naming",
      "READMEs: include dataset info, methodology, results with visualizations",
      "Repo names: 'sentiment-analysis-nlp', 'housing-price-predictor'",
      "Profile README with skills, Kaggle link, and research interests",
    ],
    changes: [
      "Renamed all repos to be descriptive of the project/model",
      "Added comprehensive READMEs explaining the data science process",
      "Included result visualizations and model performance metrics in READMEs",
      "Created a profile README using the Data Science template",
      "Linked Kaggle profile and added certifications",
      "Made school assignments private, kept only best projects",
    ],
    result: "Got an internship offer after the interviewer mentioned being impressed by the GitHub profile.",
  },
];

export default function ExamplesPage() {
  return (
    <div className="mx-auto max-w-5xl px-4 sm:px-6 py-12">
      <div className="mb-10">
        <h1 className="text-3xl font-bold">Before/After Examples</h1>
        <p className="mt-3 text-muted-foreground text-lg">
          Real-world examples of how small changes can transform a GitHub
          profile from forgettable to hireable. Each example includes the time
          invested and the outcome.
        </p>
      </div>

      <div className="space-y-12">
        {examples.map((example, i) => (
          <div key={i}>
            <div className="mb-4 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
              <div>
                <h2 className="text-xl font-bold">{example.title}</h2>
                <p className="text-sm text-muted-foreground">
                  {example.context}
                </p>
              </div>
              <Badge variant="outline" className="text-xs shrink-0 w-fit">
                {example.timeInvested}
              </Badge>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
              <Card className="border-destructive/30">
                <CardContent className="p-5">
                  <div className="flex items-center gap-2 mb-4">
                    <div className="h-2 w-2 rounded-full bg-destructive" />
                    <span className="font-semibold text-destructive text-sm">
                      Before
                    </span>
                  </div>
                  <ul className="space-y-2 text-sm text-muted-foreground">
                    {example.before.map((item, j) => (
                      <li key={j} className="flex gap-2">
                        <span className="text-destructive shrink-0">x</span>
                        {item}
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>

              <Card className="border-emerald/30">
                <CardContent className="p-5">
                  <div className="flex items-center gap-2 mb-4">
                    <div className="h-2 w-2 rounded-full bg-emerald" />
                    <span className="font-semibold text-emerald text-sm">
                      After
                    </span>
                  </div>
                  <ul className="space-y-2 text-sm text-muted-foreground">
                    {example.after.map((item, j) => (
                      <li key={j} className="flex gap-2">
                        <span className="text-emerald shrink-0">+</span>
                        {item}
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            </div>

            <Card>
              <CardContent className="p-5">
                <h3 className="text-sm font-semibold mb-3">
                  What Changed
                </h3>
                <ul className="space-y-2 text-sm text-muted-foreground">
                  {example.changes.map((change, j) => (
                    <li key={j} className="flex gap-2">
                      <Badge
                        variant="outline"
                        className="shrink-0 text-xs h-5"
                      >
                        {j + 1}
                      </Badge>
                      {change}
                    </li>
                  ))}
                </ul>
                {example.result && (
                  <div className="mt-4 pt-4 border-t border-border">
                    <p className="text-sm text-emerald">
                      <span className="font-medium">Result:</span>{" "}
                      {example.result}
                    </p>
                  </div>
                )}
              </CardContent>
            </Card>

            {i < examples.length - 1 && (
              <hr className="mt-12 border-border" />
            )}
          </div>
        ))}
      </div>

      {/* Real Project Example */}
      <div className="mt-16">
        <hr className="border-border mb-12" />
        <div className="mb-6">
          <Badge variant="secondary" className="mb-3">
            Live Example
          </Badge>
          <h2 className="text-xl font-bold">Real-World Project: GitReady</h2>
          <p className="text-sm text-muted-foreground mt-2">
            This site itself is an example of a well-structured GitHub project.
            See how the repository follows every best practice we recommend.
          </p>
        </div>

        <Card>
          <CardContent className="p-5">
            <div className="space-y-4">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {[
                  { label: "Descriptive name", detail: '"gitready" tells you exactly what the project does' },
                  { label: "Professional README", detail: "Badges, description, features, tech stack, getting started, project structure" },
                  { label: "Clean codebase", detail: "Well-organized src/ with logical directories: app/, components/, lib/" },
                  { label: "Meaningful commits", detail: "Each commit describes what changed and why" },
                  { label: "Tech stack badges", detail: "Next.js, TypeScript, Tailwind CSS — instantly scannable" },
                  { label: "Working setup instructions", detail: "git clone → npm install → npm run dev — tested and verified" },
                ].map((item) => (
                  <div key={item.label} className="flex gap-2">
                    <span className="text-emerald shrink-0">+</span>
                    <div>
                      <p className="text-sm font-medium">{item.label}</p>
                      <p className="text-xs text-muted-foreground">{item.detail}</p>
                    </div>
                  </div>
                ))}
              </div>
              <div className="pt-4 border-t border-border flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
                <p className="text-sm text-muted-foreground">
                  View the source code to see all these practices in action.
                </p>
                <Button asChild variant="outline" size="sm" className="shrink-0">
                  <a
                    href="https://github.com/nis1993tx/gitready"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    View on GitHub
                  </a>
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Bottom CTA */}
      <div className="mt-16 text-center">
        <h2 className="text-2xl font-bold mb-4">Your Turn</h2>
        <p className="text-muted-foreground mb-6">
          Run the checklist to see where your profile stands, then use our
          templates to make improvements. Most people finish in 2-3 hours.
        </p>
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <Button asChild size="lg">
            <Link href="/checklist">Run the Checklist</Link>
          </Button>
          <Button asChild variant="outline" size="lg">
            <Link href="/templates">Browse Templates</Link>
          </Button>
        </div>
      </div>
    </div>
  );
}
